name: Webhook receiver
on:
  push:
    branches:
      - master
      - staging
    paths:
      - webhook-receiver/**
      - .github/workflows/webhook-receiver-deploy.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16.0
      - working-directory: ./webhook-receiver/
        run: go test -ginkgo.v
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bittrance
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./webhook-receiver/
          tags: bittrance/webhook-receiver:${{ github.ref == 'refs/heads/master' && 'latest' || 'staging' }}
